/*==========================================================
Project : Multi-Touch Marketing Attribution & ROI Dashboard
Author  : Yusuf Bahrainwala
Database: PostgreSQL
Description:
This script performs marketing attribution analysis by
combining advertising spend, customer touchpoints, and
conversion data. It implements First-Touch, Last-Touch,
and Linear Attribution Models, calculates marketing KPIs,
and builds a Star Schema for Power BI reporting.
==========================================================*/
/*==========================================================
SECTION 1
Exploratory Data Analysis
==========================================================*/
SELECT
	*
FROM
	AD_SPEND;

SELECT
	*
FROM
	CONVERSIONS;

SELECT
	*
FROM
	USER_TOUCHPOINTS;

SELECT
	COUNT(DISTINCT USER_ID)
FROM
	CONVERSIONS;

SELECT
	COUNT(DISTINCT USER_ID)
FROM
	USER_TOUCHPOINTS;

SELECT
	COUNT(DISTINCT CAMPAIGN_ID)
FROM
	AD_SPEND;

SELECT
	COUNT(DISTINCT CAMPAIGN_ID)
FROM
	USER_TOUCHPOINTS;

/*==========================================================
SECTION 2
Customer Journey Construction
==========================================================*/
-- Creating User Journey Table/View
CREATE OR REPLACE VIEW USER_JOURNEY AS
SELECT
	T.USER_ID,
	T.SESSION_ID,
	T.TIMESTAMP,
	T.SOURCE,
	T.MEDIUM,
	T.CAMPAIGN_ID,
	T.CAMPAIGN_NAME,
	T.EVENT_TYPE,
	C.CONVERSION_ID,
	C.CONVERSION_TIMESTAMP,
	C.REVENUE
FROM
	USER_TOUCHPOINTS T
	JOIN CONVERSIONS C ON T.USER_ID = C.USER_ID
WHERE
	T.TIMESTAMP <= C.CONVERSION_TIMESTAMP;

SELECT
	*
FROM
	USER_JOURNEY;

SELECT
	USER_ID,
	SOURCE,
	TIMESTAMP,
	ROW_NUMBER() OVER (
		PARTITION BY
			USER_ID
		ORDER BY
			TIMESTAMP
	) AS TOUCH_ORDER
FROM
	USER_JOURNEY
ORDER BY
	USER_ID,
	TIMESTAMP
LIMIT
	30;

SELECT
	USER_ID,
	SOURCE,
	TIMESTAMP,
	ROW_NUMBER() OVER (
		PARTITION BY
			USER_ID
		ORDER BY
			TIMESTAMP
	) AS TOUCH_ORDER,
	COUNT(*) OVER (
		PARTITION BY
			USER_ID
	) AS TOTAL_TOUCHES
FROM
	USER_JOURNEY
ORDER BY
	USER_ID,
	TIMESTAMP
LIMIT
	30;

/*==========================================================
SECTION 3
First Touch Attribution
==========================================================*/
-- First-Touch Attribution Model
-- Asks "Who introduced the customer?"
CREATE OR REPLACE VIEW FIRST_TOUCH_ATTRIBUTION AS
WITH
	JOURNEY_RANKED AS (
		SELECT
			USER_ID,
			SOURCE,
			MEDIUM,
			CAMPAIGN_ID,
			CAMPAIGN_NAME,
			CONVERSION_ID,
			CONVERSION_TIMESTAMP,
			REVENUE,
			ROW_NUMBER() OVER (
				PARTITION BY
					USER_ID
				ORDER BY
					TIMESTAMP
			) AS TOUCH_ORDER
		FROM
			USER_JOURNEY
	)
SELECT
	*
FROM
	JOURNEY_RANKED
WHERE
	TOUCH_ORDER = 1;

SELECT
	*
FROM
	FIRST_TOUCH_ATTRIBUTION;

SELECT
	COUNT(*)
FROM
	FIRST_TOUCH_ATTRIBUTION;

SELECT
	SOURCE,
	COUNT(*) AS CONVERSIONS,
	SUM(REVENUE) AS ATTRIBUTED_REVENUE
FROM
	FIRST_TOUCH_ATTRIBUTION
GROUP BY
	SOURCE
ORDER BY
	ATTRIBUTED_REVENUE ASC;

-- Google is the strongest customer acquisition channel.
/*==========================================================
SECTION 3
Last Touch Attribution
==========================================================*/
-- Last-Touch Attribution Model
-- Asks "Who closed the sale?"
CREATE OR REPLACE VIEW LAST_TOUCH_ATTRIBUTION AS
WITH
	JOURNEY_RANKED AS (
		SELECT
			USER_ID,
			SOURCE,
			MEDIUM,
			CAMPAIGN_ID,
			CAMPAIGN_NAME,
			CONVERSION_ID,
			CONVERSION_TIMESTAMP,
			REVENUE,
			ROW_NUMBER() OVER (
				PARTITION BY
					USER_ID
				ORDER BY
					TIMESTAMP DESC
			) AS TOUCH_ORDER
		FROM
			USER_JOURNEY
	)
SELECT
	*
FROM
	JOURNEY_RANKED
WHERE
	TOUCH_ORDER = 1;

SELECT
	*
FROM
	LAST_TOUCH_ATTRIBUTION;

SELECT
	COUNT(*)
FROM
	LAST_TOUCH_ATTRIBUTION;

SELECT
	SOURCE,
	COUNT(*) AS CONVERSIONS,
	SUM(REVENUE) AS ATTRIBUTED_REVENUE
FROM
	LAST_TOUCH_ATTRIBUTION
GROUP BY
	SOURCE
ORDER BY
	ATTRIBUTED_REVENUE ASC;

-- Google generated the highest number of attributed conversions
-- Facebook and email are better at introducing customers than closing customers.
/*==========================================================
SECTION 3
Linear Attribution
==========================================================*/
-- Linear Attribution Model
CREATE OR REPLACE VIEW LINEAR_ATTRIBUTION AS
SELECT
	USER_ID,
	SOURCE,
	MEDIUM,
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_ID,
	CONVERSION_TIMESTAMP,
	REVENUE,
	COUNT(*) OVER (
		PARTITION BY
			USER_ID
	) AS TOTAL_TOUCHES,
	1.0 / COUNT(*) OVER (
		PARTITION BY
			USER_ID
	) AS ATTRIBUTION_WEIGHT,
	REVENUE * (
		1.0 / COUNT(*) OVER (
			PARTITION BY
				USER_ID
		)
	) AS ATTRIBUTED_REVENUE
FROM
	USER_JOURNEY;

SELECT
	*
FROM
	LINEAR_ATTRIBUTION
LIMIT
	15;

SELECT
	SOURCE,
	COUNT(*) AS ATTRIBUTED_TOUCHPOINTS,
	ROUND(SUM(ATTRIBUTED_REVENUE), 2) AS ATTRIBUTED_REVENUE
FROM
	LINEAR_ATTRIBUTION
GROUP BY
	SOURCE
ORDER BY
	ATTRIBUTED_REVENUE DESC;

-- Linear Attribution by Campaign
CREATE OR REPLACE VIEW LINEAR_CAMPAIGN_REVENUE AS
SELECT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	ROUND(SUM(ATTRIBUTED_REVENUE), 2) AS ATTRIBUTED_REVENUE,
	COUNT(DISTINCT CONVERSION_ID) AS ATTRIBUTED_CONVERSIONS
FROM
	LINEAR_ATTRIBUTION
WHERE
	CAMPAIGN_ID IS NOT NULL
GROUP BY
	CAMPAIGN_ID,
	CAMPAIGN_NAME;

SELECT
	*
FROM
	LINEAR_CAMPAIGN_REVENUE
ORDER BY
	ATTRIBUTED_REVENUE DESC
LIMIT
	10;

/*==========================================================
SECTION 3
First Touch Attribution
==========================================================*/
-- Spend by Campaign View
CREATE OR REPLACE VIEW CAMPAIGN_SPEND AS
SELECT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	SUM(SPEND) AS TOTAL_SPEND,
	SUM(CLICKS) AS TOTAL_CLICKS,
	SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS
FROM
	AD_SPEND
GROUP BY
	CAMPAIGN_ID,
	CAMPAIGN_NAME;

SELECT
	*
FROM
	CAMPAIGN_SPEND
ORDER BY
	TOTAL_SPEND DESC;

-- Create Campaign Performance View
CREATE OR REPLACE VIEW CAMPAIGN_PERFORMANCE AS
SELECT
	S.CAMPAIGN_ID,
	S.CAMPAIGN_NAME,
	S.TOTAL_SPEND,
	S.TOTAL_CLICKS,
	S.TOTAL_IMPRESSIONS,
	COALESCE(R.ATTRIBUTED_REVENUE, 0) AS ATTRIBUTED_REVENUE,
	COALESCE(R.ATTRIBUTED_CONVERSIONS, 0) AS ATTRIBUTED_CONVERSIONS
FROM
	CAMPAIGN_SPEND S
	LEFT JOIN LINEAR_CAMPAIGN_REVENUE R ON S.CAMPAIGN_ID = R.CAMPAIGN_ID;

SELECT
	*
FROM
	CAMPAIGN_PERFORMANCE;

/*==========================================================
SECTION 3
Marketing KPIs
==========================================================*/
-- Create Campaign KPIs 
CREATE OR REPLACE VIEW CAMPAIGN_KPIS AS
SELECT
	*,
	ROUND(ATTRIBUTED_REVENUE / NULLIF(TOTAL_SPEND, 0), 2) AS ROAS
FROM
	CAMPAIGN_PERFORMANCE;

SELECT
	CAMPAIGN_NAME,
	TOTAL_SPEND,
	ATTRIBUTED_REVENUE,
	ATTRIBUTED_CONVERSIONS,
	ROAS
FROM
	CAMPAIGN_KPIS
ORDER BY
	ROAS DESC
LIMIT
	10;

CREATE OR REPLACE VIEW CAMPAIGN_KPIS_2 AS
SELECT
	*,
	ROUND(ATTRIBUTED_REVENUE / NULLIF(TOTAL_SPEND, 0), 2) AS ROAS,
	ROUND(
		TOTAL_SPEND / NULLIF(ATTRIBUTED_CONVERSIONS, 0),
		2
	) AS CAC
FROM
	CAMPAIGN_PERFORMANCE;

SELECT
	CAMPAIGN_NAME,
	TOTAL_SPEND,
	ATTRIBUTED_REVENUE,
	ATTRIBUTED_CONVERSIONS,
	ROAS,
	CAC
FROM
	CAMPAIGN_KPIS_2
ORDER BY
	CAC DESC
LIMIT
	10;

/*==========================================================
SECTION 3
Star Schema Data Modeling
==========================================================*/
-- Dim Campaign table
CREATE OR REPLACE VIEW DIM_CAMPAIGN AS
SELECT DISTINCT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	PLATFORM,
	CHANNEL
FROM
	AD_SPEND;

SELECT
	COUNT(*)
FROM
	DIM_CAMPAIGN;

-- Dim Date Table
DROP VIEW IF EXISTS DIM_DATE;

CREATE VIEW DIM_DATE AS
SELECT DISTINCT
	DATE,
	EXTRACT(
		YEAR
		FROM
			DATE
	) AS YEAR,
	EXTRACT(
		MONTH
		FROM
			DATE
	) AS MONTH_NO,
	TO_CHAR(DATE, 'Month') AS MONTH_NAME,
	TO_CHAR(DATE, 'Mon') AS MONTH_SHORT,
	EXTRACT(
		QUARTER
		FROM
			DATE
	) AS QUARTER,
	EXTRACT(
		DAY
		FROM
			DATE
	) AS DAY,
	TO_CHAR(DATE, 'Day') AS WEEKDAY_NAME,
	EXTRACT(
		DOW
		FROM
			DATE
	) AS WEEKDAY_NO
FROM
	FACT_ATTRIBUTION
ORDER BY
	DATE;

SELECT
	COUNT(*)
FROM
	DIM_DATE;

-- Fact Attribution View
CREATE OR REPLACE VIEW FACT_ATTRIBUTION AS
-- First Touch
SELECT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE AS DATE,
	'First Touch' AS MODEL_TYPE,
	SUM(REVENUE) AS ATTRIBUTED_REVENUE,
	COUNT(*) AS ATTRIBUTED_CONVERSIONS
FROM
	FIRST_TOUCH_ATTRIBUTION
GROUP BY
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE
UNION ALL
-- Last Touch
SELECT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE AS DATE,
	'Last Touch' AS MODEL_TYPE,
	SUM(REVENUE) AS ATTRIBUTED_REVENUE,
	COUNT(*) AS ATTRIBUTED_CONVERSIONS
FROM
	LAST_TOUCH_ATTRIBUTION
GROUP BY
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE
UNION ALL
-- Linear
SELECT
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE AS DATE,
	'Linear' AS MODEL_TYPE,
	SUM(ATTRIBUTED_REVENUE) AS ATTRIBUTED_REVENUE,
	COUNT(DISTINCT CONVERSION_ID) AS ATTRIBUTED_CONVERSIONS
FROM
	LINEAR_ATTRIBUTION
GROUP BY
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CONVERSION_TIMESTAMP::DATE;

SELECT
	*
FROM
	FACT_ATTRIBUTION;

SELECT
	*
FROM
	FACT_ATTRIBUTION
LIMIT
	5;